// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = String(import.meta.env.VITE_SUPABASE_URL || "").trim();
const SUPABASE_PUBLISHABLE_KEY = String(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "").trim();
const HAS_SUPABASE_CONFIG = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

// Prevent runtime crash when Vercel env vars are missing.
// App will still load, but auth requests will fail until env is configured.
const SAFE_SUPABASE_URL = HAS_SUPABASE_CONFIG
  ? SUPABASE_URL
  : "https://invalid-project.supabase.co";
const SAFE_SUPABASE_PUBLISHABLE_KEY = HAS_SUPABASE_CONFIG
  ? SUPABASE_PUBLISHABLE_KEY
  : "invalid-publishable-key";

if (!HAS_SUPABASE_CONFIG && typeof window !== "undefined") {
  console.error(
    "[Supabase] Missing VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY. Set them in Vercel Project Settings -> Environment Variables.",
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SAFE_SUPABASE_URL, SAFE_SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
